//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhachSan.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentService
    {
        public int PaymentService_ID { get; set; }
        public Nullable<int> payment_id { get; set; }
        public Nullable<int> Useage { get; set; }
        public Nullable<int> Reservation_id { get; set; }
        public Nullable<int> Service_ID { get; set; }
    
        public virtual Service Service { get; set; }
        public virtual Reservation Reservation { get; set; }
    }
}
