//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhachSan.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentService
    {
        public int PaymentService_ID { get; set; }
        public Nullable<int> payment_id { get; set; }
        public Nullable<int> guest_id { get; set; }
    
        public virtual Payment Payment { get; set; }
    }
}
