//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhachSan.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public int Service_ID { get; set; }
        public string Service_Name { get; set; }
        public Nullable<int> unitPrice { get; set; }
        public string unit { get; set; }
    }
}
